### ISSUE TITLE
Package failed updates, dependency or conflict validation - Issue

### ISSUE THREAD

**Issue by naix86** [2gis/Winium.Mobile#149]
10:31:50 [DEBUG] Waiting for a connection...
10:32:05 [DEBUG] ACCEPTED REQUEST POST /session HTTP/1.1
10:32:05 [INFO] COMMAND newSession
Hi, 

Why I keep getting this issue?

Generate only x86 appx; run winium and it return this error everytime.

Please help

{
  "desiredCapabilities": {
    "devicename": "Mobile Emulator 10.0.10586.0 WVGA 4 inch 1GB",
    "app": "C:\Users\xxx\Documents\Visual Studio 2015\Projects\App1\App1\App1.UWP\bin\x86\Debug\App1.UWP_1.0.5.0_x86_Debug.appx"
  }
}
10:32:05 [INFO] Target emulator: 'Mobile Emulator 10.0.10586.0 WVGA 4 inch 1GB'
10:32:05 [DEBUG] RESPONSE:
OK:
{
  "sessionId": "b35c4259-801c-4ad7-9cd7-40bfb4a0c31a",
  "status": 33,
  "value": {
    "error": "session not created",
    "stacktrace": "   at Winium.StoreApps.Driver.CommandExecutors.NewSessionExecutor.DoImpl() in d:\Projects\windows-universal-app-driver\Winium\Winium.StoreApps.Driver\CommandExecutors\NewSessionExecutor.cs:line 38\r\n   at Winium.StoreApps.Driver.CommandExecutors.CommandExecutorBase.Do() in d:\Projects\windows-universal-app-driver\Winium\Winium.StoreApps.Driver\CommandExecutors\CommandExecutorBase.cs:line 42",
    "message": "Package failed updates, dependency or conflict validation.\r\n"

**Comment by NickAb** [comment]
Are you trying to deploy UWP app to Windows 10?

**Comment by naix86** [comment]
Hi Nick,

I am deploying UWP to windows 10.

**Comment by NickAb** [comment]
Deploying UWP has not been tested or research well enough. Here are some options you can try:

First try reseting emulator by restoring default snapshot and redeploying with driver, there seems to be dependencies conflict for some apps when trying to deploy app to emulator using driver, after it was deployed to the same emulator using Visual Studio. 

If it does not work, then you could try reseting emulator and deploying dependencies explicitly. There should be a folder called `Dependencies` next to app bundle. Try listing them in [dependencies capability](https://github.com/2gis/Winium.StoreApps/wiki/Capabilities#dependencies)

If that one does not work, try reseting emulator, deploying the app using Visual Studio, then deploying only app bundle (delete dependencies folder). If that one works, then you can create snapshot of emulator with correct dependencies installed by Visual Studio and set that snapshot as default.

**Comment by naix86** [comment]
sadly, it doesn't work

**Comment by NickAb** [comment]
Please try building x86 package only. Make sure that there is no arm or x64 dependencies in package folder. See https://github.com/2gis/Winium.StoreApps/issues/116#issuecomment-163085104 for similar issue.

**Comment by NickAb** [comment]
Closing as dup of #116 to gather all discussion and workarounds in one place
