### ISSUE TITLE
Any CodeCverage Tool which i can use with my automation to get coverage ?

### ISSUE THREAD

**Issue by padmaja2812** [2gis/Winium.Mobile#170]

**Comment by NickAb** [comment]
Sorry, I do not know if there is any code coverage tool that can be used. I think code coverage code be gathered when only running mstest unit tests on Windows Phone, I was not able to find any info on how to gather code coverage the other way, even when running Coded UI tests.

If you could find any docs on running code coverage programatically or when running Coded UI tests, please link it here.

**Comment by NickAb** [comment]
Also, I am not sure if code coverage is a good metric for UI tests, shouldn't it be requirement coverage. Code coverage is good for unit testing.
