### ISSUE TITLE
Handling system dialog

### ISSUE THREAD

**Issue by madhu-sv** [2gis/Winium.Mobile#179]
I have a situation where I need to tap on system permission dialog. Is there a way to do this? If not then is there a plan to support this in the future?

Any inputs on this will be appreciated.

**Comment by NickAb** [comment]
Currently there is no support for system dialogs. System dialogs are shown in a separate window then AUT. As a result driver does not know anything about system dialogs and it actually gets blocked when modal system dialog is shown.

Current workaround for system dialogs is to try clicking using coordinates whrn you assume the dialogs is show. This might be very flaky.

**Comment by madhu-sv** [comment]
Fixed it.
