### ISSUE TITLE
Add additional properties to Winium.StoreApps.InnerServer PageSourceCommand

### ISSUE THREAD

**Issue by goldbillka** [2gis/Winium.Mobile#66]
Currently PageSourceCommand returns only few base attributes of WiniumElement. If extend it, we can display in Inspector additional properties depending on the type of FrameworkElement. 

For example, if FrameworkElement is TextBox, then add FontSize, FontStyle, Foreground and other Windows.UI.Xaml.Controls.TextBlock properties.

**Comment by NickAb** [comment]
Additional properties can be requested using GetElementAttribute command if needed.
